
version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: es-container-new
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m 
    ports:
      - "9200:9200"
    volumes:
      - /root/TraceX/data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - attack-range

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana-container
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - attack-range
  
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie-honeypot
    restart: always
    ports:
      - "2223:2222"
    volumes:
      - /root/TraceX/infrastructure/range/honeypots/cowrie/etc:/cowrie/cowrie-git/etc
      - /root/TraceX/infrastructure/range/honeypots/cowrie/var/log:/cowrie/cowrie-git/var/log
    networks:
      attack-range:
        ipv4_address: 172.20.0.100

  zeek:
    image: zeek/zeek:latest
    container_name: zeek-collector
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    tty: true
    stdin_open: true
    # 核心 1：设置工作目录为 logs
    working_dir: /usr/local/zeek/logs
    # 核心 2：必须加入 -C 参数！同时确保 local.zeek 路径正确
    command: /usr/local/zeek/bin/zeek -C -i eth0 /usr/local/zeek/share/zeek/site/local.zeek
    volumes:
      # 映射配置文件
      - ./collector/network_collector/zeek_config/local.zeek:/usr/local/zeek/share/zeek/site/local.zeek
      - ./collector/network_collector/zeek_config/node.cfg:/usr/local/zeek/etc/node.cfg
      # 核心 3：挂载路径必须和 working_dir 一致，否则你在宿主机看不到新生成的日志
      - /root/TraceX/data/zeek-logs:/usr/local/zeek/logs
    restart: always


  internal-host:
    build: ./infrastructure/range/internal-host
    container_name: internal-host-node
    networks:
      attack-range:
        ipv4_address: 172.20.0.40
    volumes:
      - /root/TraceX/data/internal-logs:/var/log
    cap_add:
      - AUDIT_CONTROL
      - AUDIT_WRITE

  dc-server:
    build: ./infrastructure/range/dc-server
    container_name: dc-server-node
    networks:
      attack-range:
        ipv4_address: 172.20.0.50
    volumes:
      - /root/TraceX/data/dc-logs:/var/log
    privileged: true
    cap_add:
      - NET_ADMIN

networks:
  attack-range:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
