version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: es-container
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m 
    ports:
      - "9200:9200"
    volumes:
      - /root/TraceX/data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - attack-range

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana-container
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - attack-range
  
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie-honeypot
    restart: always
    ports:
      - "2222:2222"
    volumes:
      - /root/TraceX/infrastructure/range/honeypots/cowrie/etc:/cowrie/cowrie-git/etc
      - /root/TraceX/infrastructure/range/honeypots/cowrie/var/log:/cowrie/cowrie-git/var/log
    networks:
      attack-range:
        ipv4_address: 172.20.0.100

  zeek:
    image: zeek/zeek:latest
    container_name: zeek-collector
    network_mode: host 
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      # 将 Zeek 日志映射到宿主机，方便手动运行的 Python 脚本读取
      - /root/TraceX/data/zeek-logs:/opt/zeek/logs
      - ./collector/network_collector/zeek_config:/opt/zeek/etc
    restart: always

networks:
  attack-range:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24