version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: es-container
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m 
    ports:
      - "9200:9200"
    volumes:
      - /root/TraceX/data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - attack-range

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana-container
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - attack-range
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie-honeypot
    restart: always
    ports:
      - "2222:2222"
    volumes:
      - /root/TraceX/infrastructure/range/honeypots/cowrie/etc:/cowrie/cowrie-git/etc
      - /root/TraceX/infrastructure/range/honeypots/cowrie/var/log:/cowrie/cowrie-git/var/log
      - /root/TraceX/infrastructure/range/honeypots/cowrie/var/lib:/cowrie/cowrie-git/var/lib
    networks:
      attack-range:
        ipv4_address: 172.20.0.100

  zeek:
    image: zeek/zeek:latest
    container_name: zeek-collector
    # 必须使用 host 模式才能监听网卡流量
    network_mode: host 
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      # 将生成的日志挂载出来，方便 Filebeat 或解析器读取
      - zeek-logs:/opt/zeek/logs
      # 挂载自定义配置文件
      - ./collector/network_collector/zeek_config:/opt/zeek/etc
    restart: always


  # Wordpot: WordPress 蜜罐
  wordpot:
    image: dtagdevsec/wordpot:24.04.1
    container_name: wordpot-honeypot
    restart: always
    ports:
      - "8080:80"  # 模拟 Web 服务
    volumes:
      # 将日志挂载到项目标准路径
      - /root/TraceX/infrastructure/range/honeypots/wordpot/logs:/var/log/wordpot
    networks:
      attack-range:
        ipv4_address: 172.20.0.101 

networks:
  attack-range:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  zeek-logs: